# Generated by Django 3.2.14 on 2023-04-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=20)),
                ('auther', models.CharField(max_length=20)),
                ('strem', models.CharField(choices=[('IT', 'IT'), ('CS', 'CS'), ('MEC', 'MEC'), ('Civil', 'Civil'), ('Electronics', 'Electronics'), ('Other', 'Other')], max_length=255)),
                ('descrioption', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(max_length=2000)),
                ('date', models.DateField(auto_now_add=True)),
                ('student_Repaly', models.CharField(max_length=255)),
                ('Teacher', models.CharField(max_length=255)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teacher.books')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
