# Generated by Django 3.2.14 on 2023-04-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendations',
            name='Teacher',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recomendations',
            name='student_Repaly',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
