# Generated by Django 3.2.14 on 2023-04-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_alter_books_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='price',
        ),
        migrations.AddField(
            model_name='books',
            name='book_image',
            field=models.FileField(default=1, upload_to='book_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='referencelink',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
