# Generated by Django 3.2.14 on 2023-04-10 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datamodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('btech_branch', models.CharField(max_length=10)),
                ('physics_10', models.FloatField()),
                ('chemistry_10', models.FloatField()),
                ('maths_10', models.FloatField()),
                ('physics_12', models.FloatField()),
                ('chemistry_12', models.FloatField()),
                ('maths_12', models.FloatField()),
                ('btech_sem1', models.FloatField()),
                ('btech_sem2', models.FloatField()),
                ('btech_sem3', models.FloatField()),
                ('btech_sem4', models.FloatField()),
                ('mode_study', models.CharField(max_length=10)),
                ('study_time', models.IntegerField()),
                ('attendance', models.FloatField(blank=True, null=True)),
                ('iq_marks', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
