# Generated by Django 3.2.14 on 2023-04-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='prediction_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='study_time',
            field=models.FloatField(),
        ),
    ]
